### ISSUE TITLE
Add color configuration for new virtual jump labels

### ISSUE THREAD

**Issue by paletochen** [base16-project/base16-helix#11]
Helix has introduced in [24.03 version](https://helix-editor.com/news/release-24-03-highlights/) a new jump mode and the themes need to be updated to work properly.

For example, **base16-google-dark** looks like below when jump mode is enabled through `gw` shortcut

![image](https://github.com/tinted-theming/base16-helix/assets/109062850/34fb06f3-2e53-40e5-988d-f83208e0c202)

where you can see that the labels maintain the same color (green) as the normal text.

I suggest adding the following line:

`"ui.virtual.jump-label" = { fg = "base0A", modifiers = ["bold"] }`
 or 
`"ui.virtual.jump-label" = { fg = "base0D", modifiers = ["bold"] }`

which would make the theme to look like this (with `base0A`):

![image](https://github.com/tinted-theming/base16-helix/assets/109062850/3193697b-53de-497b-8017-0028495c7444)

------

Other "random" themes would look like this:

**base16-dracula**
![image](https://github.com/tinted-theming/base16-helix/assets/109062850/a35debe8-3ad6-4c16-8eeb-9d0bb93d3792)

**base16-embers-light**
![image](https://github.com/tinted-theming/base16-helix/assets/109062850/e8c40cfc-1dda-4bfd-88f6-7084717ab5b9)

**base16-catppuccin-mocha**
![image](https://github.com/tinted-theming/base16-helix/assets/109062850/96858a77-04d2-4a3e-9372-34612b5e05f6)

**base16-tomorrow-night-eighties**
![image](https://github.com/tinted-theming/base16-helix/assets/109062850/f5d78376-1e4a-4efb-b75f-675622e8538a)

Though feel free to use whatever other color combination you may find better looking :)

Thanks

**Comment by paletochen** [comment]
Another interesting approach would be:

`"ui.virtual.jump-label" = { modifiers = ["bold", "reversed"] }`

or just

`"ui.virtual.jump-label" = { modifiers = ["reversed"] }`

**base16-google-dark** would look like this:
![image](https://github.com/tinted-theming/base16-helix/assets/109062850/e7012cc3-db47-4d2a-ab82-12105bd78890)


instead of:

![image](https://github.com/tinted-theming/base16-helix/assets/109062850/a672e91e-0382-4e7b-a84d-330aae04e677)

**Comment by krgn** [comment]
Hi, thank you for putting in the work. I'm quite excited this is supported now 😄 

My personal preference would be one of your first two suggestions (not `reversed`).

**Comment by paletochen** [comment]
> Hi, thank you for putting in the work. I'm quite excited this is supported now 😄
> 
> My personal preference would be one of your first two suggestions (not `reversed`).

I have no personal preference yet, I am experimenting with both approaches and depending on the type of code|file I may like one or the other.
But if i would have to choose right now, i would probably also go for one of the 1st suggestions, without the `reversed` mode

**Comment by JamyGolden** [comment]
Thanks for creating the issue. I've created a PR: https://github.com/tinted-theming/base16-helix/pull/14

**Comment by JamyGolden** [comment]
I'll close this since I've merged the above PR.
