### ISSUE TITLE
consider changing `ui.virtual.inlay-hint`

### ISSUE THREAD

**Issue by Ciflire** [base16-project/base16-helix#13]
This is how helix looks with inlay hint enabled
![image](https://github.com/tinted-theming/base16-helix/assets/39668077/a27bca95-5218-4844-9d93-d6f22e8e92ff)

I cannot see them tbh, i don't know how that can addect the rest of the UI, i'm just suggesting thing here
I'm using [stylix](https://github.com/danth/stylix) for this so i cannot easily modify the theme myself
PS: the theme is not modified between this repo and my pc, that's why i'm reporting this here

**Comment by joefiorini** [comment]
This is how it looks for me too, only using a different theme. Inlay hints are unreadable.
